import { ENDPOINTS } from './endpoints';

export const API_ENDPOINTS = {
    // Dashboard
    DASHBOARD: ENDPOINTS.DASHBOARD,

    // Admin
    ADMIN_ARTICLES: ENDPOINTS.ADMIN.POSTS,
    ADMIN_LOCATIONS: ENDPOINTS.ADMIN.LOCATIONS,
    ADMIN_SOURCES: ENDPOINTS.ADMIN.SOURCES,
    ADMIN_MEMBERS: ENDPOINTS.ADMIN.MEMBERS,
    ADMIN_TAG_CATEGORIES: ENDPOINTS.ADMIN.TAGS,
    ADMIN_CHARACTERS: ENDPOINTS.ADMIN.PERSONS,
    ADMIN_PERIODS: ENDPOINTS.ADMIN.PERIODS,
    ADMIN_EVENTS: ENDPOINTS.ADMIN.EVENTS,
    ADMIN_ENGAGEMENTS_PENDING: ENDPOINTS.ADMIN.ENGAGEMENTS_PENDING,
    ADMIN_SETTINGS: ENDPOINTS.SETTINGS.BASE,

    // Detail aliases
    USER_ARTICLE_DETAIL: ENDPOINTS.ADMIN.POSTS,
    USER_CHARACTER_DETAIL: ENDPOINTS.ADMIN.PERSONS,
    USER_EVENT_DETAIL: ENDPOINTS.ADMIN.EVENTS,
    USER_LOCATION_DETAIL: ENDPOINTS.ADMIN.LOCATIONS,
    USER_PERIOD_DETAIL: ENDPOINTS.ADMIN.PERIODS,
    USER_RECORD_DETAIL: ENDPOINTS.ADMIN.SOURCES,

    // Collection aliases
    ADMIN_RECORDS: ENDPOINTS.ADMIN.SOURCES,
    USER_ARTICLES: ENDPOINTS.ADMIN.POSTS,
    USER_CHARACTERS: ENDPOINTS.ADMIN.PERSONS,
    USER_EVENTS: ENDPOINTS.ADMIN.EVENTS,
    USER_LOCATIONS: ENDPOINTS.ADMIN.LOCATIONS,
    USER_PERIODS: ENDPOINTS.ADMIN.PERIODS,
    USER_RECORDS: ENDPOINTS.ADMIN.SOURCES,
    USER_PROFILE_HISTORY: ENDPOINTS.MEMBER.ME_HISTORY,

    // AI / RAG
    RAG_CHAT: ENDPOINTS.RAG.CHAT,


    PUBLIC_ENGAGEMENTS: ENDPOINTS.PUBLIC.ENGAGEMENTS,
};

export { ENDPOINTS };
export * from './index';