import { ENDPOINTS } from './endpoints';

export const API_ENDPOINTS = {
    // Dashboard
    DASHBOARD: ENDPOINTS.DASHBOARD,

    // Admin
    ADMIN_ARTICLES: ENDPOINTS.ADMIN.POSTS,
    ADMIN_LOCATIONS: ENDPOINTS.ADMIN.LOCATIONS,
    ADMIN_SOURCES: ENDPOINTS.ADMIN.SOURCES,
    ADMIN_MEMBERS: ENDPOINTS.ADMIN.MEMBERS,
    ADMIN_TAG_CATEGORIES: ENDPOINTS.ADMIN.TAGS,
    ADMIN_CHARACTERS: ENDPOINTS.ADMIN.PERSONS,
    ADMIN_PERIODS: ENDPOINTS.ADMIN.PERIODS,
    ADMIN_EVENTS: ENDPOINTS.ADMIN.EVENTS,
    ADMIN_ENGAGEMENTS_PENDING: ENDPOINTS.ADMIN.ENGAGEMENTS_PENDING,
    ADMIN_SETTINGS: ENDPOINTS.SETTINGS.BASE,

    // Detail aliases
    USER_ARTICLE_DETAIL: ENDPOINTS.ADMIN.POSTS_BY_ID,
    USER_CHARACTER_DETAIL: ENDPOINTS.ADMIN.PERSONS_BY_ID,
    USER_EVENT_DETAIL: ENDPOINTS.ADMIN.EVENTS_BY_ID,
    USER_LOCATION_DETAIL: ENDPOINTS.ADMIN.LOCATIONS_BY_ID,
    USER_PERIOD_DETAIL: ENDPOINTS.ADMIN.PERIODS_BY_ID,
    USER_RECORD_DETAIL: ENDPOINTS.ADMIN.SOURCES_BY_ID,

    // Collection aliases
    ADMIN_RECORDS: ENDPOINTS.ADMIN.SOURCES,
    USER_ARTICLES: ENDPOINTS.ADMIN.POSTS,
    USER_CHARACTERS: ENDPOINTS.ADMIN.PERSONS,
    USER_EVENTS: ENDPOINTS.ADMIN.EVENTS,
    USER_LOCATIONS: ENDPOINTS.ADMIN.LOCATIONS,
    USER_PERIODS: ENDPOINTS.ADMIN.PERIODS,
    USER_RECORDS: ENDPOINTS.ADMIN.SOURCES,
    USER_PROFILE_HISTORY: ENDPOINTS.MEMBER.ME_HISTORY,

    // AI / RAG
    RAG_CHAT: ENDPOINTS.RAG.CHAT,

    PERIOD_COLORS: ENDPOINTS.MOCK.PERIOD_COLORS,
    TAG_COLORS: ENDPOINTS.MOCK.TAG_COLORS,
    LOCATION_TYPE_COLORS: ENDPOINTS.MOCK.LOCATION_TYPE_COLORS,
    ADMIN_AI: ENDPOINTS.MOCK.ADMIN_AI,
    ADMIN_METADATA: ENDPOINTS.MOCK.ADMIN_METADATA,
};

export { ENDPOINTS };
export * from './index';